theme: minima
title: GitHub Website
author: Dileepa Bandara
email: contact.dileepabandara@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there! This is my example website which is built with GitHub.

# social links
twitter_username: _dileepabandara # DO NOT include the @ character, or else the build will fail!
github_username:  dileepabandara # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
